### GET All users
GET http://localhost:5000/users/
Accept: application/json
Content-Type: application/json


### POST Create new user
POST http://localhost:5000/signup
Content-Type: application/json
Accept: application/json

{
  "email": "a@11.ru",
  "password": "123456"
}


### Get User Profile
GET http://localhost:5000/users/me
Content-Type: application/json
Accept: application/json


### PATCH Update user profile
PATCH http://localhost:5000/users/me
Content-Type: application/json
Accept: application/json

{
  "name": "new name",
  "about": "updated about"
}


### PATCH Update user avatar
PATCH http://localhost:5000/users/me/avatar
Content-Type: application/json
Accept: application/json

{
  "avatar": "http://example.com/new-avatar.jpg"
}


### Login
POST http://localhost:5000/signin
Content-Type: application/json
Accept: application/json

{
  "email": "a@11.ru",
  "password": "123456"
}